  TWITTER_KEY: wwlKdQ1JwuOBDetRQBxnhB6Mk
  TWITTER_SECRET: 1zw2CVsKaxHYDdbvR4YpKkZCDhK35FwpEhYP6Q9287s3LOxmoA

  FACEBOOK_KEY: 795468393896951
  FACEBOOK_SECRET: 16cf02da2a9ac72c910e33a3615abf0b

  GOOGLE_CLIENT_ID: 165233668232-pc0cfajop9qhsd581g6hl2i2otioia65.apps.googleusercontent.com
  GOOGLE_SECRET: giIJEB-8vfysz3GCgRcXSVI6

  LINKEDIN_KEY: 77e4t57ls4f8hi
  LINKEDIN_SECRET: xl2fkaIDHGc5nYp7

  SSL_CERT_FILE: /etc/openssl